name: 'Auto Assign Review Teams'
description: 'Send review requests to teams all members'
author: 'Robert Wiesner'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  teams:
    description: 'Teams (works best with Auto Assignment) - team1, team 2'
    required: true
  organisation:
    description: 'Name of your organisation'
    required: true
  include-draft:
    description: 'If set to true, DRAFT PRs will also be covered (default=false)'
    required: false

runs:
  using: 'node12'
  main: 'lib/index.js'
